### ISSUE TITLE
(Request) Appimage and/or Flatpak support for Steam Deck

### ISSUE THREAD

**Issue by Star-X555** [obsidian-level-maker/Obsidian#500] opened 2022-09-29 01:15 UTC
I've read in other issue pages that flatpak experimentation is happening, but I'd honestly appreciate an official statement about when/if Obsidian will have an appimage or flatpak, as Steam Deck users cannot compile source code themselves without making significant changes to the immutable filesystem that get erased immediately following a SteamOS update.

**Comment by ghost** [comment] 2022-09-29 20:06
The user who was working on Flatpak support, HugLifeTiZ, has been off the radar for a while. Although I did fold in and maintain his custom fork of FLTK that adds the Zenity file chooser, there are no other active efforts towards making a Flatpak/AppImage/Snap/whathaveyou at the moment. So, the answer would be "it might happen, but I have no clue when."

**Comment by ghost** [comment] 2022-10-01 00:29
I'll also note that there is value to doing this in my opinion, but that it should only be something performed for stable releases. So I guess a reasonable estimate would be around the time V20 becomes the stable release, for which I also have no estimate :/

**Comment by LinuxToasty** [comment] 2022-10-05 14:48
I have not done any Flatpak packaging before, but I have created an appimage of Obsidian. 
I am a linux user and I created one to save compiling on my various machines. 

Happy to help out if useful.

**Comment by ghost** [comment] 2022-10-05 15:38
If you have a summary or reproducible steps to build the AppImage for it, I would love to take a peek. I've never built anything in either AppImage or the Flatpak/Snap formats, so I wouldn't really know where to start.

**Comment by LinuxToasty** [comment] 2022-10-05 16:27
Off the top of my head as I am at work-

Compile as normal.

Create AppDir directory.
Inside the directory create usr

Inside the usr directory create bin, lib, share.

Inside the bin directory create a script called obsidian.
In the script add-
#!/bin/bash
cd AppDir/usr/share/obsidian && ./obsidian "$@"

Inside the lib directory add libraries needed by obsidian to run.

Inside the share directory
add applications for the desktop file.
add icons into the icons file
add -
addons  data     games     modules   scripts  tools
attic   engines  language  theme
and the obsidian executable.

Move to directory above the AppDir and run-
./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage.

Works for me. Only issue is Appimages are read only, so if I have addons I have to add them to the addons folder and recreate the appimage.

I think the other directories are fine being read only. But you know better than me on this one.

I think the only other caveat is that Appimages need to run on the oldest supported version of Ubuntu.
So I compile and add the libraries from this.

There are probably better explanations but it works for me :-)

**Comment by LinuxToasty** [comment] 2022-10-05 16:55
The other resolution for Steam Deck users is to use the "Bottles" wine flatpak. Obsidian also works perfectly on Wine.

**Comment by ghost** [comment] 2022-10-05 22:28
Thanks for the instructions! That seems pretty automatable, so if that's the case it might be pretty easy to generate AppImages even for Unstable builds. I'll try to shoot for the next Unstable update to offer an AppImage as well for testing. I'll keep this open for now until that's done.

**Comment by LinuxToasty** [comment] 2022-10-06 07:16
Great stuff.  I will have a look at Flatpak as well to see if I can get it working.

**Comment by ghost** [comment] 2022-10-09 17:15
https://github.com/dashodanger/Obsidian/releases/tag/Obsidian-Current-Unstable

I've included a 64-bit AppImage in the current unstable release for testing.

**Comment by LinuxToasty** [comment] 2022-10-10 07:28
Brilliant news.. I have got a flatpak build locally that I am just ironing out. 
I will send info as soon as I have done testing..
Thank you for building the appimage. I will test this evening to make sure I didn't miss anything.. Great work..

**Comment by ghost** [comment] 2022-10-11 00:20
> Brilliant news.. I have got a flatpak build locally that I am just ironing out. I will send info as soon as I have done testing.. Thank you for building the appimage. I will test this evening to make sure I didn't miss anything.. Great work..

I will say that the AppImage worked for me on a fresh Ubuntu install, but a fellow user who tried it on Arch was out of luck...not sure if I neglected to package something or not.

**Comment by LinuxToasty** [comment] 2022-10-11 07:44
Works for me on Debian, Ubuntu and Fedora. Will spin up an Arch VM to see what the error is.. 
Oh the headaches of packaging for Linux..

**Comment by Phytolizer** [comment] 2022-10-18 06:45
Just saw this thread, I'm the Arch user. Here is the error if you didn't see it already:
```
Inconsistency detected by ld.so: dl-call-libc-early-init.c: 37: _dl_call_libc_early_init: Assertion `sym != NULL' failed!
```

**Comment by ghost** [comment] 2022-11-23 01:49
Moving this to Discussion as it's not a release blocker

**Closed as completed** 2022-11-23 01:49 UTC
Labels: logistics
